import type {
  Customer,
  Employee,
  Load,
  Location,
  ProductType,
  SystemUser,
} from "./types";

export const LOCATIONS: Location[] = [
  { id: "loc-savannah", name: "Savannah, GA", region: "Southeast" },
  { id: "loc-charlotte", name: "Charlotte, NC", region: "Southeast" },
  { id: "loc-dallas", name: "Dallas, TX", region: "South Central" },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cust-geodis",
    contactName: "John Reyes",
    email: "j.reyes@geodis.com",
    phone: "(704) 555-0142",
    displayName: "Geodis",
    legalCompanyName: "Geodis Logistics LLC",
    locationIds: ["loc-charlotte", "loc-dallas"],
    status: "active",
  },
  {
    id: "cust-crane",
    contactName: "Maria Chen",
    email: "m.chen@craneworldwide.com",
    phone: "(912) 555-0198",
    displayName: "Crane Worldwide",
    legalCompanyName: "Crane Worldwide Logistics LLC",
    locationIds: ["loc-savannah"],
    status: "active",
  },
  {
    id: "cust-ferrero",
    contactName: "Sam Patel",
    email: "s.patel@ferreroretail.com",
    phone: "(214) 555-0117",
    displayName: "Ferrero Retail Group",
    legalCompanyName: "Ferrero Retail Group Inc.",
    locationIds: ["loc-dallas"],
    status: "active",
  },
  {
    id: "cust-oldco",
    contactName: "Denise Ward",
    email: "d.ward@oldco-example.com",
    phone: "(704) 555-0100",
    displayName: "OldCo Distribution",
    legalCompanyName: "OldCo Distribution Inc.",
    locationIds: ["loc-charlotte"],
    status: "archived",
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    name: "Marcus Bell",
    email: "marcus.bell@example.com",
    phone: "(704) 555-0111",
    address: "118 Freight Rd, Charlotte, NC",
    hourlyRate: 17.5,
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-2",
    name: "Ana Ortiz",
    email: "ana.ortiz@example.com",
    phone: "(704) 555-0133",
    address: "42 Dock St, Charlotte, NC",
    hourlyRate: 18,
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-3",
    name: "Trevon Hicks",
    email: "trevon.hicks@example.com",
    phone: "(912) 555-0177",
    address: "9 Port Blvd, Savannah, GA",
    hourlyRate: 19,
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-4",
    name: "Grace Lin",
    email: "grace.lin@example.com",
    phone: "(912) 555-0166",
    address: "230 Warehouse Way, Savannah, GA",
    hourlyRate: 18.5,
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-5",
    name: "Devon Marsh",
    email: "devon.marsh@example.com",
    phone: "(214) 555-0155",
    address: "77 Pallet Ln, Dallas, TX",
    hourlyRate: 17,
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-6",
    name: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "(214) 555-0122",
    address: "310 Sortline Dr, Dallas, TX",
    hourlyRate: 17.75,
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-7",
    name: "Walt Kessler",
    email: "walt.kessler@example.com",
    phone: "(704) 555-0188",
    address: "5 Loading Ct, Charlotte, NC",
    hourlyRate: 16.5,
    locationId: "loc-charlotte",
    status: "archived",
  },
];

export const PRODUCT_TYPES: ProductType[] = [
  {
    id: "pt-geodis-reboxing",
    customerId: "cust-geodis",
    locationId: "loc-charlotte",
    name: "Reboxing",
    status: "active",
    rateLines: [
      {
        id: "rl-1",
        unit: "case",
        billBase: 200,
        billThreshold: 2700,
        billOverRate: 0.1,
        payThreshold: 2000,
        payOverRate: 0.05,
        payBonus: 0,
      },
      {
        id: "rl-2",
        unit: "sort",
        billBase: 0,
        billThreshold: 5,
        billOverRate: 10,
        payThreshold: 5,
        payOverRate: 4,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-geodis-pallet",
    customerId: "cust-geodis",
    locationId: "loc-dallas",
    name: "Pallet Building",
    status: "active",
    rateLines: [
      {
        id: "rl-3",
        unit: "pallet",
        billBase: 150,
        billThreshold: 40,
        billOverRate: 3.5,
        payThreshold: 40,
        payOverRate: 1.75,
        payBonus: 25,
      },
    ],
  },
  {
    id: "pt-crane-banding",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Solar Panel Banding",
    status: "active",
    rateLines: [
      {
        id: "rl-4",
        unit: "case",
        billBase: 225,
        billThreshold: 1800,
        billOverRate: 0.12,
        payThreshold: 1500,
        payOverRate: 0.06,
        payBonus: 0,
      },
      {
        id: "rl-5",
        unit: "lb",
        billBase: 0,
        billThreshold: 50,
        billOverRate: 0.02,
        payThreshold: 50,
        payOverRate: 0.01,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-crane-scanning",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Solar Panel Scanning",
    status: "active",
    rateLines: [
      {
        id: "rl-6",
        unit: "case",
        billBase: 175,
        billThreshold: 1600,
        billOverRate: 0.09,
        payThreshold: 1400,
        payOverRate: 0.045,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-ferrero-sorting",
    customerId: "cust-ferrero",
    locationId: "loc-dallas",
    name: "Case Sorting",
    status: "active",
    rateLines: [
      {
        id: "rl-7",
        unit: "case",
        billBase: 190,
        billThreshold: 2200,
        billOverRate: 0.08,
        payThreshold: 1900,
        payOverRate: 0.04,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-crane-legacy-scan",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Legacy Crate Scanning",
    status: "archived",
    rateLines: [
      {
        id: "rl-8",
        unit: "case",
        billBase: 150,
        billThreshold: 1200,
        billOverRate: 0.08,
        payThreshold: 1200,
        payOverRate: 0.04,
        payBonus: 0,
      },
    ],
  },
];

export const LOADS: Load[] = [
  {
    id: "load-195",
    ticketNumber: 195,
    date: "2026-07-01",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "12",
    containerNumber: "TCLU 884321",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88213"],
    sorts: 6,
    cases: 2840,
    weight: 3100,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:02", clockOut: "13:41" },
      { employeeId: "emp-2", clockIn: "06:05", clockOut: "13:39" },
    ],
    status: "complete",
    billedAmount: 214,
    payoutAmount: 42,
  },
  {
    id: "load-200",
    ticketNumber: 200,
    date: "2026-07-02",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "4",
    containerNumber: "MSCU 552190",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77410", "PO-77411"],
    sorts: 4,
    cases: 1650,
    weight: 4200,
    assignments: [
      { employeeId: "emp-3", clockIn: "07:00", clockOut: "15:03" },
      { employeeId: "emp-4", clockIn: "07:00", clockOut: "15:01" },
    ],
    status: "complete",
    billedAmount: 260,
    payoutAmount: 130,
  },
  {
    id: "load-204",
    ticketNumber: 204,
    date: "2026-07-03",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "9",
    containerNumber: "HLXU 213045",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91002"],
    sorts: 3,
    cases: 2390,
    weight: 2650,
    assignments: [{ employeeId: "emp-5", clockIn: "08:15", clockOut: "14:52" }],
    status: "complete",
    billedAmount: 205,
    payoutAmount: 38,
  },
  {
    id: "load-208",
    ticketNumber: 208,
    date: "2026-07-04",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-pallet",
    doorNumber: "7",
    containerNumber: "GESU 440217",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-88420"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [{ employeeId: "emp-2", clockIn: "09:00", clockOut: null }],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
  },
  {
    id: "load-211",
    ticketNumber: 211,
    date: "2026-07-05",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-scanning",
    doorNumber: "2",
    containerNumber: "TEMU 106688",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77502"],
    sorts: 2,
    cases: 1120,
    weight: 1900,
    assignments: [{ employeeId: "emp-3", clockIn: "06:30", clockOut: "11:10" }],
    status: "void",
    billedAmount: 0,
    payoutAmount: 0,
  },
  {
    id: "load-212",
    ticketNumber: 212,
    date: "2026-07-05",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "5",
    containerNumber: "CMAU 771122",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91055"],
    sorts: 5,
    cases: 2510,
    weight: 2800,
    assignments: [{ employeeId: "emp-6", clockIn: "07:45", clockOut: "16:02" }],
    status: "complete",
    billedAmount: 214.8,
    payoutAmount: 44.4,
  },
  {
    id: "load-206",
    ticketNumber: 206,
    date: "2026-06-24",
    locationId: "loc-charlotte",
    customerId: "cust-oldco",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "3",
    containerNumber: "OLCU 990011",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-50021"],
    sorts: 5,
    cases: 2650,
    weight: 2900,
    assignments: [{ employeeId: "emp-1", clockIn: "06:00", clockOut: "12:30" }],
    status: "archived",
    billedAmount: 200,
    payoutAmount: 0,
  },
];

export const SYSTEM_USERS: SystemUser[] = [
  {
    id: "user-admin",
    name: "Rick Alvarez",
    email: "rick@dockmaster3pl.com",
    role: "admin",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "user-lead-savannah",
    name: "Josie Turner",
    email: "josie.turner@example.com",
    role: "lead",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "user-geodis-portal",
    name: "John Reyes",
    email: "j.reyes@geodis.com",
    role: "customer",
    locationId: "loc-charlotte",
    status: "active",
  },
];
