import type {
  Customer,
  Employee,
  Load,
  Location,
  ProductType,
  SystemUser,
} from "./types";

export const LOCATIONS: Location[] = [
  {
    id: "loc-savannah",
    name: "Savannah, GA",
    region: "Southeast",
    code: "SAV",
    group: "East Coast",
    addressL1: "100 Portside Dr",
    city: "Savannah",
    state: "GA",
    postalCode: "31401",
    timezone: "America/New_York",
    status: "active",
    shiftStart: "07:00",
    shiftEnd: "15:00",
  },
  {
    id: "loc-charlotte",
    name: "Charlotte, NC",
    region: "Southeast",
    code: "CLT",
    group: "East Coast",
    addressL1: "200 Freight Ln",
    city: "Charlotte",
    state: "NC",
    postalCode: "28202",
    timezone: "America/New_York",
    status: "active",
    shiftStart: "06:00",
    shiftEnd: "14:00",
  },
  {
    id: "loc-dallas",
    name: "Dallas, TX",
    region: "South Central",
    code: "DAL",
    group: "Central",
    addressL1: "300 Logistics Blvd",
    city: "Dallas",
    state: "TX",
    postalCode: "75201",
    timezone: "America/Chicago",
    status: "active",
    shiftStart: "08:00",
    shiftEnd: "16:00",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cust-geodis",
    contactName: "John Reyes",
    email: "j.reyes@geodis.com",
    phone: "(704) 555-0142",
    displayName: "Geodis",
    legalCompanyName: "Geodis Logistics LLC",
    locationIds: ["loc-charlotte", "loc-dallas"],
    status: "active",
  },
  {
    id: "cust-crane",
    contactName: "Maria Chen",
    email: "m.chen@craneworldwide.com",
    phone: "(912) 555-0198",
    displayName: "Crane Worldwide",
    legalCompanyName: "Crane Worldwide Logistics LLC",
    locationIds: ["loc-savannah"],
    status: "active",
  },
  {
    id: "cust-ferrero",
    contactName: "Sam Patel",
    email: "s.patel@ferreroretail.com",
    phone: "(214) 555-0117",
    displayName: "Ferrero Retail Group",
    legalCompanyName: "Ferrero Retail Group Inc.",
    locationIds: ["loc-dallas"],
    status: "active",
  },
  {
    id: "cust-oldco",
    contactName: "Denise Ward",
    email: "d.ward@oldco-example.com",
    phone: "(704) 555-0100",
    displayName: "OldCo Distribution",
    legalCompanyName: "OldCo Distribution Inc.",
    locationIds: ["loc-charlotte"],
    status: "archived",
  },
  {
    id: "cust-triumph",
    contactName: "Luis Vega",
    email: "l.vega@triumphlogistics.com",
    phone: "(912) 555-0234",
    displayName: "Triumph Logistics",
    legalCompanyName: "Triumph Logistics LLC",
    locationIds: ["loc-savannah", "loc-charlotte"],
    status: "active",
  },
  {
    id: "cust-redstone",
    contactName: "Naomi Cross",
    email: "n.cross@redstonegoods.com",
    phone: "(214) 555-0345",
    displayName: "Redstone Goods",
    legalCompanyName: "Redstone Goods Inc.",
    locationIds: ["loc-dallas"],
    status: "active",
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    name: "Marcus Bell",
    email: "marcus.bell@example.com",
    phone: "(704) 555-0111",
    address: "118 Freight Rd, Charlotte, NC",
    hourlyRate: 17.5,
    category: "labour",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-2",
    name: "Ana Ortiz",
    email: "ana.ortiz@example.com",
    phone: "(704) 555-0133",
    address: "42 Dock St, Charlotte, NC",
    hourlyRate: 18,
    category: "forklift",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-3",
    name: "Trevon Hicks",
    email: "trevon.hicks@example.com",
    phone: "(912) 555-0177",
    address: "9 Port Blvd, Savannah, GA",
    hourlyRate: 19,
    category: "operator",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-4",
    name: "Grace Lin",
    email: "grace.lin@example.com",
    phone: "(912) 555-0166",
    address: "230 Warehouse Way, Savannah, GA",
    hourlyRate: 18.5,
    category: "checker",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-5",
    name: "Devon Marsh",
    email: "devon.marsh@example.com",
    phone: "(214) 555-0155",
    address: "77 Pallet Ln, Dallas, TX",
    hourlyRate: 17,
    category: "loader",
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-6",
    name: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "(214) 555-0122",
    address: "310 Sortline Dr, Dallas, TX",
    hourlyRate: 17.75,
    category: "sorter",
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-7",
    name: "Walt Kessler",
    email: "walt.kessler@example.com",
    phone: "(704) 555-0188",
    address: "5 Loading Ct, Charlotte, NC",
    hourlyRate: 16.5,
    category: "clerk",
    locationId: "loc-charlotte",
    status: "archived",
  },
  {
    id: "emp-8",
    name: "Rosa Mendoza",
    email: "rosa.mendoza@example.com",
    phone: "(704) 555-0211",
    address: "88 Bay St, Charlotte, NC",
    hourlyRate: 17.25,
    category: "sorter",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-9",
    name: "Jamal Carter",
    email: "jamal.carter@example.com",
    phone: "(704) 555-0222",
    address: "12 Gate Rd, Charlotte, NC",
    hourlyRate: 18.5,
    category: "forklift",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "emp-10",
    name: "Elena Vasquez",
    email: "elena.vasquez@example.com",
    phone: "(912) 555-0244",
    address: "45 River St, Savannah, GA",
    hourlyRate: 17,
    category: "labour",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-11",
    name: "Darnell Fox",
    email: "darnell.fox@example.com",
    phone: "(912) 555-0255",
    address: "301 Wharf Ave, Savannah, GA",
    hourlyRate: 19.5,
    category: "forklift",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "emp-12",
    name: "Sofia Crane",
    email: "sofia.crane@example.com",
    phone: "(214) 555-0266",
    address: "16 Beltline Dr, Dallas, TX",
    hourlyRate: 17.5,
    category: "checker",
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-13",
    name: "Raymond Zhao",
    email: "raymond.zhao@example.com",
    phone: "(214) 555-0277",
    address: "52 Dock Row, Dallas, TX",
    hourlyRate: 18,
    category: "operator",
    locationId: "loc-dallas",
    status: "active",
  },
  {
    id: "emp-14",
    name: "Keisha Barlow",
    email: "keisha.barlow@example.com",
    phone: "(912) 555-0288",
    address: "78 Pallet Way, Savannah, GA",
    hourlyRate: 17.75,
    category: "sorter",
    locationId: "loc-savannah",
    status: "active",
  },
];

export const PRODUCT_TYPES: ProductType[] = [
  {
    id: "pt-geodis-reboxing",
    customerId: "cust-geodis",
    locationId: "loc-charlotte",
    name: "Reboxing",
    status: "active",
    rateLines: [
      {
        id: "rl-1",
        unit: "case",
        billBase: 200,
        billThreshold: 2700,
        billOverRate: 0.1,
        payThreshold: 2000,
        payOverRate: 0.05,
        payBonus: 0,
      },
      {
        id: "rl-2",
        unit: "sort",
        billBase: 0,
        billThreshold: 5,
        billOverRate: 10,
        payThreshold: 5,
        payOverRate: 4,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-geodis-pallet",
    customerId: "cust-geodis",
    locationId: "loc-dallas",
    name: "Pallet Building",
    status: "active",
    rateLines: [
      {
        id: "rl-3",
        unit: "pallet",
        billBase: 150,
        billThreshold: 40,
        billOverRate: 3.5,
        payThreshold: 40,
        payOverRate: 1.75,
        payBonus: 25,
      },
    ],
  },
  {
    id: "pt-crane-banding",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Solar Panel Banding",
    status: "active",
    rateLines: [
      {
        id: "rl-4",
        unit: "case",
        billBase: 225,
        billThreshold: 1800,
        billOverRate: 0.12,
        payThreshold: 1500,
        payOverRate: 0.06,
        payBonus: 0,
      },
      {
        id: "rl-5",
        unit: "lb",
        billBase: 0,
        billThreshold: 50,
        billOverRate: 0.02,
        payThreshold: 50,
        payOverRate: 0.01,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-crane-scanning",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Solar Panel Scanning",
    status: "active",
    rateLines: [
      {
        id: "rl-6",
        unit: "case",
        billBase: 175,
        billThreshold: 1600,
        billOverRate: 0.09,
        payThreshold: 1400,
        payOverRate: 0.045,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-ferrero-sorting",
    customerId: "cust-ferrero",
    locationId: "loc-dallas",
    name: "Case Sorting",
    status: "active",
    rateLines: [
      {
        id: "rl-7",
        unit: "case",
        billBase: 190,
        billThreshold: 2200,
        billOverRate: 0.08,
        payThreshold: 1900,
        payOverRate: 0.04,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-crane-legacy-scan",
    customerId: "cust-crane",
    locationId: "loc-savannah",
    name: "Legacy Crate Scanning",
    status: "archived",
    rateLines: [
      {
        id: "rl-8",
        unit: "case",
        billBase: 150,
        billThreshold: 1200,
        billOverRate: 0.08,
        payThreshold: 1200,
        payOverRate: 0.04,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-triumph-unloading",
    customerId: "cust-triumph",
    locationId: "loc-savannah",
    name: "Container Unloading",
    status: "active",
    rateLines: [
      {
        id: "rl-9",
        unit: "case",
        billBase: 180,
        billThreshold: 2400,
        billOverRate: 0.07,
        payThreshold: 2000,
        payOverRate: 0.035,
        payBonus: 0,
      },
    ],
  },
  {
    id: "pt-triumph-rework",
    customerId: "cust-triumph",
    locationId: "loc-charlotte",
    name: "Rework & Labeling",
    status: "active",
    rateLines: [
      {
        id: "rl-10",
        unit: "case",
        billBase: 210,
        billThreshold: 1800,
        billOverRate: 0.11,
        payThreshold: 1600,
        payOverRate: 0.055,
        payBonus: 50,
      },
    ],
  },
  {
    id: "pt-redstone-consolidation",
    customerId: "cust-redstone",
    locationId: "loc-dallas",
    name: "Load Consolidation",
    status: "active",
    rateLines: [
      {
        id: "rl-11",
        unit: "pallet",
        billBase: 175,
        billThreshold: 35,
        billOverRate: 4.0,
        payThreshold: 35,
        payOverRate: 2.0,
        payBonus: 20,
      },
    ],
  },
];

export const LOADS: Load[] = [
  // ── Original loads (kept for history) ──────────────────────────
  {
    id: "load-195",
    ticketNumber: 195,
    date: "2026-07-01",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "12",
    containerNumber: "TCLU 884321",
    trailerNumber: "TRL-4421",
    sealNumber: "SL-88213",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88213"],
    sorts: 6,
    cases: 2840,
    weight: 3100,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:02", clockOut: "13:41" },
      { employeeId: "emp-2", clockIn: "06:05", clockOut: "13:39" },
    ],
    status: "complete",
    billedAmount: 214,
    payoutAmount: 42,
    lastUpdatedAt: "2026-07-01T13:41:00Z",
  },
  {
    id: "load-200",
    ticketNumber: 200,
    date: "2026-07-02",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "4",
    containerNumber: "MSCU 552190",
    trailerNumber: "TRL-2205",
    sealNumber: "SL-77410",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77410", "PO-77411"],
    sorts: 4,
    cases: 1650,
    weight: 4200,
    assignments: [
      { employeeId: "emp-3", clockIn: "07:00", clockOut: "15:03" },
      { employeeId: "emp-4", clockIn: "07:00", clockOut: "15:01" },
    ],
    status: "complete",
    billedAmount: 260,
    payoutAmount: 130,
    lastUpdatedAt: "2026-07-02T15:03:00Z",
  },
  {
    id: "load-204",
    ticketNumber: 204,
    date: "2026-07-03",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "9",
    containerNumber: "HLXU 213045",
    trailerNumber: "TRL-8891",
    sealNumber: "",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91002"],
    sorts: 3,
    cases: 2390,
    weight: 2650,
    assignments: [{ employeeId: "emp-5", clockIn: "08:15", clockOut: "14:52" }],
    status: "complete",
    billedAmount: 205,
    payoutAmount: 38,
    lastUpdatedAt: "2026-07-03T14:52:00Z",
  },
  {
    id: "load-208",
    ticketNumber: 208,
    date: "2026-07-04",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-pallet",
    doorNumber: "7",
    containerNumber: "GESU 440217",
    trailerNumber: "",
    sealNumber: "",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-88420"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [{ employeeId: "emp-2", clockIn: "09:00", clockOut: null }],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-04T09:00:00Z",
  },
  {
    id: "load-211",
    ticketNumber: 211,
    date: "2026-07-05",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-scanning",
    doorNumber: "2",
    containerNumber: "TEMU 106688",
    trailerNumber: "TRL-3301",
    sealNumber: "SL-77502",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77502"],
    sorts: 2,
    cases: 1120,
    weight: 1900,
    assignments: [{ employeeId: "emp-3", clockIn: "06:30", clockOut: "11:10" }],
    status: "void",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-05T11:10:00Z",
  },
  {
    id: "load-212",
    ticketNumber: 212,
    date: "2026-07-05",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "5",
    containerNumber: "MSCU 782193",
    trailerNumber: "TRL-8842",
    sealNumber: "SL-472190",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91055"],
    sorts: 5,
    cases: 2510,
    weight: 2800,
    assignments: [
      { employeeId: "emp-5", clockIn: "07:35", clockOut: "16:18" },
      { employeeId: "emp-6", clockIn: "07:40", clockOut: "16:05" },
    ],
    status: "complete",
    billedAmount: 214.8,
    payoutAmount: 44.4,
    lastUpdatedAt: "2026-07-05T16:18:00Z",
  },
  {
    id: "load-206",
    ticketNumber: 206,
    date: "2026-06-24",
    locationId: "loc-charlotte",
    customerId: "cust-oldco",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "3",
    containerNumber: "OLCU 990011",
    trailerNumber: "TRL-5510",
    sealNumber: "SL-50021",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-50021"],
    sorts: 5,
    cases: 2650,
    weight: 2900,
    assignments: [{ employeeId: "emp-1", clockIn: "06:00", clockOut: "12:30" }],
    status: "archived",
    billedAmount: 200,
    payoutAmount: 0,
    lastUpdatedAt: "2026-06-24T12:30:00Z",
  },

  // ── Week of Jul 18–24 — Charlotte (Geodis + Triumph) ──────────
  {
    id: "load-213",
    ticketNumber: 213,
    date: "2026-07-18",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "14",
    containerNumber: "BMOU 320145",
    trailerNumber: "TRL-4502",
    sealNumber: "SL-88401",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88401"],
    sorts: 7,
    cases: 3120,
    weight: 3400,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:00", clockOut: "14:10" },
      { employeeId: "emp-8", clockIn: "06:05", clockOut: "14:00" },
      { employeeId: "emp-9", clockIn: "06:10", clockOut: "14:05" },
    ],
    status: "complete",
    billedAmount: 242,
    payoutAmount: 56,
    lastUpdatedAt: "2026-07-18T14:10:00Z",
  },
  {
    id: "load-214",
    ticketNumber: 214,
    date: "2026-07-18",
    locationId: "loc-charlotte",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-rework",
    doorNumber: "8",
    containerNumber: "TCNU 774322",
    trailerNumber: "TRL-5512",
    sealNumber: "SL-88520",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-88520", "PO-88521"],
    sorts: 4,
    cases: 1950,
    weight: 2100,
    assignments: [
      { employeeId: "emp-2", clockIn: "06:30", clockOut: "13:15" },
      { employeeId: "emp-1", clockIn: "06:30", clockOut: "13:20" },
    ],
    status: "complete",
    billedAmount: 226.5,
    payoutAmount: 38.25,
    lastUpdatedAt: "2026-07-18T13:20:00Z",
  },
  {
    id: "load-215",
    ticketNumber: 215,
    date: "2026-07-19",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "11",
    containerNumber: "GESU 501224",
    trailerNumber: "TRL-4503",
    sealNumber: "SL-88610",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88610"],
    sorts: 5,
    cases: 2680,
    weight: 2950,
    assignments: [
      { employeeId: "emp-8", clockIn: "06:00", clockOut: "13:40" },
      { employeeId: "emp-9", clockIn: "06:00", clockOut: "13:35" },
    ],
    status: "complete",
    billedAmount: 208,
    payoutAmount: 34,
    lastUpdatedAt: "2026-07-19T13:40:00Z",
  },
  {
    id: "load-216",
    ticketNumber: 216,
    date: "2026-07-20",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "15",
    containerNumber: "MSCU 601883",
    trailerNumber: "TRL-4510",
    sealNumber: "SL-88740",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88740"],
    sorts: 8,
    cases: 3350,
    weight: 3700,
    assignments: [
      { employeeId: "emp-1", clockIn: "05:55", clockOut: "14:15" },
      { employeeId: "emp-2", clockIn: "06:00", clockOut: "14:10" },
      { employeeId: "emp-9", clockIn: "06:10", clockOut: "14:05" },
    ],
    status: "complete",
    billedAmount: 265,
    payoutAmount: 67.5,
    lastUpdatedAt: "2026-07-20T14:15:00Z",
  },
  {
    id: "load-217",
    ticketNumber: 217,
    date: "2026-07-20",
    locationId: "loc-charlotte",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-rework",
    doorNumber: "10",
    containerNumber: "HLXU 450912",
    trailerNumber: "TRL-5518",
    sealNumber: "SL-88755",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-88755"],
    sorts: 3,
    cases: 1720,
    weight: 1850,
    assignments: [{ employeeId: "emp-8", clockIn: "07:00", clockOut: "12:50" }],
    status: "complete",
    billedAmount: 210,
    payoutAmount: 32.6,
    lastUpdatedAt: "2026-07-20T12:50:00Z",
  },
  {
    id: "load-218",
    ticketNumber: 218,
    date: "2026-07-21",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "13",
    containerNumber: "TCLU 992401",
    trailerNumber: "TRL-4520",
    sealNumber: "SL-88890",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88890"],
    sorts: 6,
    cases: 2890,
    weight: 3150,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:00", clockOut: "13:55" },
      { employeeId: "emp-9", clockIn: "06:05", clockOut: "14:00" },
    ],
    status: "complete",
    billedAmount: 219,
    payoutAmount: 44.5,
    lastUpdatedAt: "2026-07-21T14:00:00Z",
  },
  {
    id: "load-219",
    ticketNumber: 219,
    date: "2026-07-22",
    locationId: "loc-charlotte",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-rework",
    doorNumber: "6",
    containerNumber: "BMOU 225177",
    trailerNumber: "TRL-5530",
    sealNumber: "SL-88950",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-88950", "PO-88951"],
    sorts: 5,
    cases: 2100,
    weight: 2280,
    assignments: [
      { employeeId: "emp-2", clockIn: "06:15", clockOut: "14:20" },
      { employeeId: "emp-8", clockIn: "06:15", clockOut: "14:10" },
    ],
    status: "complete",
    billedAmount: 243,
    payoutAmount: 47.5,
    lastUpdatedAt: "2026-07-22T14:20:00Z",
  },
  {
    id: "load-220",
    ticketNumber: 220,
    date: "2026-07-22",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "12",
    containerNumber: "GESU 732098",
    trailerNumber: "TRL-4535",
    sealNumber: "SL-88970",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-88970"],
    sorts: 5,
    cases: 2760,
    weight: 3020,
    assignments: [
      { employeeId: "emp-1", clockIn: "05:50", clockOut: "13:30" },
      { employeeId: "emp-9", clockIn: "06:00", clockOut: "13:40" },
    ],
    status: "complete",
    billedAmount: 216,
    payoutAmount: 38,
    lastUpdatedAt: "2026-07-22T13:40:00Z",
  },
  {
    id: "load-221",
    ticketNumber: 221,
    date: "2026-07-23",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "14",
    containerNumber: "TCNU 881304",
    trailerNumber: "TRL-4540",
    sealNumber: "SL-89020",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-89020"],
    sorts: 7,
    cases: 3270,
    weight: 3580,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:00", clockOut: "14:35" },
      { employeeId: "emp-2", clockIn: "06:00", clockOut: "14:30" },
      { employeeId: "emp-8", clockIn: "06:05", clockOut: "14:25" },
    ],
    status: "complete",
    billedAmount: 257,
    payoutAmount: 63.5,
    lastUpdatedAt: "2026-07-23T14:35:00Z",
  },
  {
    id: "load-222",
    ticketNumber: 222,
    date: "2026-07-23",
    locationId: "loc-charlotte",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-rework",
    doorNumber: "9",
    containerNumber: "MSCU 449002",
    trailerNumber: "TRL-5545",
    sealNumber: "SL-89035",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-89035"],
    sorts: 4,
    cases: 1830,
    weight: 1990,
    assignments: [{ employeeId: "emp-9", clockIn: "06:30", clockOut: "13:10" }],
    status: "complete",
    billedAmount: 213.3,
    payoutAmount: 32.65,
    lastUpdatedAt: "2026-07-23T13:10:00Z",
  },
  // Active loads — Charlotte (today Jul 24)
  {
    id: "load-223",
    ticketNumber: 223,
    date: "2026-07-24",
    locationId: "loc-charlotte",
    customerId: "cust-geodis",
    productTypeId: "pt-geodis-reboxing",
    doorNumber: "11",
    containerNumber: "HLXU 615093",
    trailerNumber: "TRL-4550",
    sealNumber: "SL-89100",
    vendor: "Southern Freight Co",
    poNumbers: ["PO-89100"],
    sorts: 4,
    cases: 1420,
    weight: 1580,
    assignments: [
      { employeeId: "emp-1", clockIn: "06:00", clockOut: null },
      { employeeId: "emp-8", clockIn: "06:00", clockOut: null },
      { employeeId: "emp-9", clockIn: "06:05", clockOut: null },
    ],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T06:00:00Z",
  },
  {
    id: "load-224",
    ticketNumber: 224,
    date: "2026-07-24",
    locationId: "loc-charlotte",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-rework",
    doorNumber: "8",
    containerNumber: "BMOU 338721",
    trailerNumber: "TRL-5555",
    sealNumber: "SL-89110",
    vendor: "Piedmont Trucking",
    poNumbers: ["PO-89110"],
    sorts: 2,
    cases: 950,
    weight: 1040,
    assignments: [{ employeeId: "emp-2", clockIn: "07:15", clockOut: null }],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T07:15:00Z",
  },

  // ── Week of Jul 18–24 — Savannah (Crane + Triumph) ────────────
  {
    id: "load-225",
    ticketNumber: 225,
    date: "2026-07-18",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "3",
    containerNumber: "MSCU 809112",
    trailerNumber: "TRL-2210",
    sealNumber: "SL-77620",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77620"],
    sorts: 5,
    cases: 1920,
    weight: 4600,
    assignments: [
      { employeeId: "emp-3", clockIn: "07:00", clockOut: "15:10" },
      { employeeId: "emp-10", clockIn: "07:05", clockOut: "15:05" },
    ],
    status: "complete",
    billedAmount: 251.4,
    payoutAmount: 55.2,
    lastUpdatedAt: "2026-07-18T15:10:00Z",
  },
  {
    id: "load-226",
    ticketNumber: 226,
    date: "2026-07-18",
    locationId: "loc-savannah",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-unloading",
    doorNumber: "6",
    containerNumber: "TCNU 552190",
    trailerNumber: "TRL-2215",
    sealNumber: "SL-77630",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77630"],
    sorts: 3,
    cases: 2580,
    weight: 3100,
    assignments: [
      { employeeId: "emp-4", clockIn: "07:30", clockOut: "14:50" },
      { employeeId: "emp-11", clockIn: "07:30", clockOut: "14:45" },
    ],
    status: "complete",
    billedAmount: 192.6,
    payoutAmount: 40.3,
    lastUpdatedAt: "2026-07-18T14:50:00Z",
  },
  {
    id: "load-227",
    ticketNumber: 227,
    date: "2026-07-19",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-scanning",
    doorNumber: "5",
    containerNumber: "HLXU 990123",
    trailerNumber: "TRL-2220",
    sealNumber: "SL-77700",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77700"],
    sorts: 2,
    cases: 1480,
    weight: 1750,
    assignments: [
      { employeeId: "emp-10", clockIn: "06:45", clockOut: "12:20" },
      { employeeId: "emp-14", clockIn: "06:45", clockOut: "12:15" },
    ],
    status: "complete",
    billedAmount: 180,
    payoutAmount: 33.6,
    lastUpdatedAt: "2026-07-19T12:20:00Z",
  },
  {
    id: "load-228",
    ticketNumber: 228,
    date: "2026-07-20",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "1",
    containerNumber: "GESU 301887",
    trailerNumber: "TRL-2230",
    sealNumber: "SL-77750",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77750", "PO-77751"],
    sorts: 6,
    cases: 2100,
    weight: 5100,
    assignments: [
      { employeeId: "emp-3", clockIn: "06:55", clockOut: "15:20" },
      { employeeId: "emp-4", clockIn: "07:00", clockOut: "15:10" },
      { employeeId: "emp-11", clockIn: "07:00", clockOut: "15:15" },
    ],
    status: "complete",
    billedAmount: 291,
    payoutAmount: 78,
    lastUpdatedAt: "2026-07-20T15:20:00Z",
  },
  {
    id: "load-229",
    ticketNumber: 229,
    date: "2026-07-20",
    locationId: "loc-savannah",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-unloading",
    doorNumber: "7",
    containerNumber: "BMOU 719224",
    trailerNumber: "TRL-2235",
    sealNumber: "SL-77770",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77770"],
    sorts: 4,
    cases: 2710,
    weight: 3350,
    assignments: [
      { employeeId: "emp-10", clockIn: "07:10", clockOut: "15:00" },
    ],
    status: "complete",
    billedAmount: 201.7,
    payoutAmount: 44.85,
    lastUpdatedAt: "2026-07-20T15:00:00Z",
  },
  {
    id: "load-230",
    ticketNumber: 230,
    date: "2026-07-21",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-scanning",
    doorNumber: "4",
    containerNumber: "TCLU 567891",
    trailerNumber: "TRL-2240",
    sealNumber: "SL-77830",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77830"],
    sorts: 3,
    cases: 1620,
    weight: 1880,
    assignments: [
      { employeeId: "emp-4", clockIn: "07:00", clockOut: "13:10" },
      { employeeId: "emp-14", clockIn: "07:00", clockOut: "13:00" },
    ],
    status: "complete",
    billedAmount: 186.8,
    payoutAmount: 37.8,
    lastUpdatedAt: "2026-07-21T13:10:00Z",
  },
  {
    id: "load-231",
    ticketNumber: 231,
    date: "2026-07-22",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "2",
    containerNumber: "MSCU 444712",
    trailerNumber: "TRL-2250",
    sealNumber: "SL-77890",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77890"],
    sorts: 5,
    cases: 1880,
    weight: 4450,
    assignments: [
      { employeeId: "emp-3", clockIn: "07:00", clockOut: "14:55" },
      { employeeId: "emp-11", clockIn: "07:00", clockOut: "14:50" },
    ],
    status: "complete",
    billedAmount: 246,
    payoutAmount: 51,
    lastUpdatedAt: "2026-07-22T14:55:00Z",
  },
  {
    id: "load-232",
    ticketNumber: 232,
    date: "2026-07-22",
    locationId: "loc-savannah",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-unloading",
    doorNumber: "8",
    containerNumber: "TCNU 392084",
    trailerNumber: "TRL-2255",
    sealNumber: "SL-77910",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77910"],
    sorts: 2,
    cases: 2350,
    weight: 2850,
    assignments: [
      { employeeId: "emp-10", clockIn: "07:20", clockOut: "13:45" },
      { employeeId: "emp-14", clockIn: "07:20", clockOut: "13:40" },
    ],
    status: "complete",
    billedAmount: 185,
    payoutAmount: 32.5,
    lastUpdatedAt: "2026-07-22T13:45:00Z",
  },
  {
    id: "load-233",
    ticketNumber: 233,
    date: "2026-07-23",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-banding",
    doorNumber: "3",
    containerNumber: "HLXU 228330",
    trailerNumber: "TRL-2260",
    sealNumber: "SL-77960",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-77960"],
    sorts: 4,
    cases: 1740,
    weight: 4100,
    assignments: [
      { employeeId: "emp-3", clockIn: "06:50", clockOut: "14:30" },
      { employeeId: "emp-4", clockIn: "07:00", clockOut: "14:35" },
    ],
    status: "complete",
    billedAmount: 238.8,
    payoutAmount: 48,
    lastUpdatedAt: "2026-07-23T14:35:00Z",
  },
  // Active — Savannah (today Jul 24)
  {
    id: "load-234",
    ticketNumber: 234,
    date: "2026-07-24",
    locationId: "loc-savannah",
    customerId: "cust-crane",
    productTypeId: "pt-crane-scanning",
    doorNumber: "5",
    containerNumber: "GESU 405116",
    trailerNumber: "TRL-2265",
    sealNumber: "SL-78000",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-78000"],
    sorts: 2,
    cases: 890,
    weight: 1120,
    assignments: [
      { employeeId: "emp-4", clockIn: "07:00", clockOut: null },
      { employeeId: "emp-10", clockIn: "07:00", clockOut: null },
    ],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T07:00:00Z",
  },
  {
    id: "load-235",
    ticketNumber: 235,
    date: "2026-07-24",
    locationId: "loc-savannah",
    customerId: "cust-triumph",
    productTypeId: "pt-triumph-unloading",
    doorNumber: "1",
    containerNumber: "BMOU 902510",
    trailerNumber: "TRL-2270",
    sealNumber: "SL-78010",
    vendor: "Coastal Intermodal",
    poNumbers: ["PO-78010"],
    sorts: 2,
    cases: 760,
    weight: 940,
    assignments: [
      { employeeId: "emp-11", clockIn: "07:45", clockOut: null },
      { employeeId: "emp-14", clockIn: "07:45", clockOut: null },
    ],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T07:45:00Z",
  },

  // ── Week of Jul 18–24 — Dallas (Ferrero + Redstone) ───────────
  {
    id: "load-236",
    ticketNumber: 236,
    date: "2026-07-18",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "10",
    containerNumber: "MSCU 115784",
    trailerNumber: "TRL-8900",
    sealNumber: "SL-472201",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91100"],
    sorts: 4,
    cases: 2480,
    weight: 2720,
    assignments: [
      { employeeId: "emp-5", clockIn: "08:00", clockOut: "15:30" },
      { employeeId: "emp-6", clockIn: "08:05", clockOut: "15:25" },
    ],
    status: "complete",
    billedAmount: 212.4,
    payoutAmount: 43.2,
    lastUpdatedAt: "2026-07-18T15:30:00Z",
  },
  {
    id: "load-237",
    ticketNumber: 237,
    date: "2026-07-19",
    locationId: "loc-dallas",
    customerId: "cust-redstone",
    productTypeId: "pt-redstone-consolidation",
    doorNumber: "3",
    containerNumber: "TCNU 448119",
    trailerNumber: "TRL-8910",
    sealNumber: "SL-63100",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-63100", "PO-63101"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [
      { employeeId: "emp-12", clockIn: "08:10", clockOut: "14:40" },
      { employeeId: "emp-13", clockIn: "08:10", clockOut: "14:35" },
    ],
    status: "complete",
    billedAmount: 190,
    payoutAmount: 42,
    lastUpdatedAt: "2026-07-19T14:40:00Z",
  },
  {
    id: "load-238",
    ticketNumber: 238,
    date: "2026-07-19",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "7",
    containerNumber: "HLXU 762034",
    trailerNumber: "TRL-8915",
    sealNumber: "SL-472215",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91220"],
    sorts: 6,
    cases: 2810,
    weight: 3100,
    assignments: [
      { employeeId: "emp-5", clockIn: "07:50", clockOut: "16:05" },
      { employeeId: "emp-6", clockIn: "08:00", clockOut: "16:00" },
      { employeeId: "emp-12", clockIn: "08:00", clockOut: "15:55" },
    ],
    status: "complete",
    billedAmount: 238.8,
    payoutAmount: 54.4,
    lastUpdatedAt: "2026-07-19T16:05:00Z",
  },
  {
    id: "load-239",
    ticketNumber: 239,
    date: "2026-07-21",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "12",
    containerNumber: "GESU 883045",
    trailerNumber: "TRL-8920",
    sealNumber: "SL-472230",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91340"],
    sorts: 5,
    cases: 2630,
    weight: 2890,
    assignments: [
      { employeeId: "emp-5", clockIn: "08:00", clockOut: "15:50" },
      { employeeId: "emp-13", clockIn: "08:00", clockOut: "15:45" },
    ],
    status: "complete",
    billedAmount: 224.4,
    payoutAmount: 49.2,
    lastUpdatedAt: "2026-07-21T15:50:00Z",
  },
  {
    id: "load-240",
    ticketNumber: 240,
    date: "2026-07-21",
    locationId: "loc-dallas",
    customerId: "cust-redstone",
    productTypeId: "pt-redstone-consolidation",
    doorNumber: "4",
    containerNumber: "BMOU 610432",
    trailerNumber: "TRL-8925",
    sealNumber: "SL-63150",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-63150"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [
      { employeeId: "emp-6", clockIn: "08:30", clockOut: "15:10" },
      { employeeId: "emp-12", clockIn: "08:30", clockOut: "15:00" },
    ],
    status: "complete",
    billedAmount: 210,
    payoutAmount: 50,
    lastUpdatedAt: "2026-07-21T15:10:00Z",
  },
  {
    id: "load-241",
    ticketNumber: 241,
    date: "2026-07-22",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "8",
    containerNumber: "MSCU 299378",
    trailerNumber: "TRL-8930",
    sealNumber: "SL-472240",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91400"],
    sorts: 4,
    cases: 2370,
    weight: 2610,
    assignments: [
      { employeeId: "emp-5", clockIn: "08:10", clockOut: "15:20" },
      { employeeId: "emp-6", clockIn: "08:10", clockOut: "15:15" },
    ],
    status: "complete",
    billedAmount: 203.6,
    payoutAmount: 38.8,
    lastUpdatedAt: "2026-07-22T15:20:00Z",
  },
  {
    id: "load-242",
    ticketNumber: 242,
    date: "2026-07-22",
    locationId: "loc-dallas",
    customerId: "cust-redstone",
    productTypeId: "pt-redstone-consolidation",
    doorNumber: "6",
    containerNumber: "TCLU 110849",
    trailerNumber: "TRL-8935",
    sealNumber: "SL-63180",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-63180"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [
      { employeeId: "emp-12", clockIn: "08:40", clockOut: "15:55" },
      { employeeId: "emp-13", clockIn: "08:40", clockOut: "16:00" },
    ],
    status: "complete",
    billedAmount: 215,
    payoutAmount: 53,
    lastUpdatedAt: "2026-07-22T16:00:00Z",
  },
  {
    id: "load-243",
    ticketNumber: 243,
    date: "2026-07-23",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "11",
    containerNumber: "HLXU 553129",
    trailerNumber: "TRL-8940",
    sealNumber: "SL-472255",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91510"],
    sorts: 3,
    cases: 2210,
    weight: 2440,
    assignments: [
      { employeeId: "emp-5", clockIn: "07:55", clockOut: "14:40" },
      { employeeId: "emp-13", clockIn: "08:00", clockOut: "14:35" },
    ],
    status: "complete",
    billedAmount: 198,
    payoutAmount: 36,
    lastUpdatedAt: "2026-07-23T14:40:00Z",
  },
  // Active — Dallas (today Jul 24)
  {
    id: "load-244",
    ticketNumber: 244,
    date: "2026-07-24",
    locationId: "loc-dallas",
    customerId: "cust-ferrero",
    productTypeId: "pt-ferrero-sorting",
    doorNumber: "5",
    containerNumber: "GESU 320667",
    trailerNumber: "TRL-8945",
    sealNumber: "SL-472260",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-91580"],
    sorts: 3,
    cases: 1180,
    weight: 1320,
    assignments: [
      { employeeId: "emp-5", clockIn: "08:00", clockOut: null },
      { employeeId: "emp-6", clockIn: "08:00", clockOut: null },
    ],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T08:00:00Z",
  },
  {
    id: "load-245",
    ticketNumber: 245,
    date: "2026-07-24",
    locationId: "loc-dallas",
    customerId: "cust-redstone",
    productTypeId: "pt-redstone-consolidation",
    doorNumber: "9",
    containerNumber: "BMOU 771256",
    trailerNumber: "TRL-8950",
    sealNumber: "SL-63200",
    vendor: "Lone Star Carriers",
    poNumbers: ["PO-63200"],
    sorts: 0,
    cases: 0,
    weight: 0,
    assignments: [{ employeeId: "emp-12", clockIn: "08:30", clockOut: null }],
    status: "active",
    billedAmount: 0,
    payoutAmount: 0,
    lastUpdatedAt: "2026-07-24T08:30:00Z",
  },
];

export const SYSTEM_USERS: SystemUser[] = [
  {
    id: "user-admin",
    name: "Rick Alvarez",
    email: "rick@dockmaster3pl.com",
    role: "admin",
    locationId: "loc-charlotte",
    status: "active",
  },
  {
    id: "user-lead-savannah",
    name: "Josie Turner",
    email: "josie.turner@example.com",
    role: "lead",
    locationId: "loc-savannah",
    status: "active",
  },
  {
    id: "user-geodis-portal",
    name: "John Reyes",
    email: "j.reyes@geodis.com",
    role: "customer",
    locationId: "loc-charlotte",
    status: "active",
  },
];
